name = "LegendHDF5IO"
uuid = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
