[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"

[compat]
Documenter = "~0.20"
